### ISSUE TITLE
Cheerio Update to 1.0.0 is breaking Enzyme 3.11.0 for Node < 18.17.0

### ISSUE THREAD

**Issue by RaghavAgrawal-TUL-Luxury** [enzymejs/enzyme#2606] opened 2024-08-12 06:43 UTC
Currently, on npm registry Enzyme@3.11.0 dependencies look like this:
![Screenshot 2024-08-12 at 12 11 09 PM](https://github.com/user-attachments/assets/875e4420-ae93-46c1-889d-b6b6223f9ac2)

This caret(^) symbol which is updating the cheerio version for all users is breaking for our application.

Thanks for reporting an issue to us! We're glad you are using and invested in Enzyme.
Before submitting, please read over our commonly reported issues to prevent duplicates!

### All common issues

* [common issues](../blob/master/docs/common-issues.md)

### Notoriously common issues

* [Webpack build issues](../blob/master/docs/common-issues.md#webpack-build-issues)
* [Cannot find module 'react-dom/lib/ReactTestUtils'](../blob/master/docs/common-issues.md#error-cannot-find-module-react-domlibreacttestutils)
* [Query Selector fails](../blob/master/docs/common-issues.md#query-selector-fails)
* [Testing third party libraries](../blob/master/docs/common-issues.md#testing-third-party-libraries)

If you haven't found any duplicated issues, please report it with your environment!

#### API

- [ ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 
| react               | 
| react-dom           | 
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [ ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by RaghavAgrawal-TUL-Luxury** [comment] 2024-08-12 06:49
In the 'master' branch, the version of cheerio package is changed to "=1.0.0-rc.3", which is not updated in the npm registry, so publishing this change should fix the issue for older projects using node < 18.17.0.

**Comment by RaghavAgrawal-TUL-Luxury** [comment] 2024-08-12 07:05
Meanwhile, the solution for this is to add the following in package.json: 

For yarn:
`
"resolutions": {
   "cheerio": "1.0.0-rc.3"
}
`

For npm:
`
"overrides": {
   "cheerio": "1.0.0-rc.3"
}
`

**Comment by ljharb** [comment] 2024-08-12 09:38
Duplicate of #2558.

**Closed by ljharb** 2024-08-12 09:38 UTC

**Comment by EJLearner** [comment] 2024-08-12 13:21
Why was this closed as "not planned"? Will there no longer be any fixes for this library?

**Comment by ljharb** [comment] 2024-08-13 02:53
@EJLearner it wasn't, it was closed as a duplicate. See the issue it duplicates, which is fixed, and the next release of enzyme will include it.

On Github, issues are closed when the fix lands, not when the fix is published.

**Comment by hanamantk** [comment] 2024-08-26 06:19
> Meanwhile, the solution for this is to add the following in package.json:
> 
> For yarn: `"resolutions": { "cheerio": "1.0.0-rc.3" }`
> 
> For npm: `"overrides": { "cheerio": "1.0.0-rc.3" }`

@RaghavAgrawal-TUL-Luxury 
But cheerio: 1..0.0.rc.3   (rc-release candidate not recommended for production so what is the fix for prod i dont want to upgrade node version so)

**Comment by ljharb** [comment] 2024-08-26 14:28
@hanamantk theres no other option, since rc3 is the last cheerio version that’s compatible with enzyme.
