### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by daveisfera** [enzymejs/enzyme#2503] opened 2021-02-22 22:36 UTC
**Is your feature request related to a problem? Please describe.**
Currently React 17 isn't listed as a possible dependency

**Describe the solution you'd like**
Add `|| ^16.0.0` to `package.json` ( see https://github.com/enzymejs/enzyme/blob/af68eb605f1c62050e99a297014a505387ece0ac/packages/enzyme-adapter-utils/package.json#L50 )

**Describe alternatives you've considered**
Set to `>=0.13.x`

**Comment by ljharb** [comment] 2021-02-22 22:39
`>= 0.13` would be highly dangerous, since enzyme *doesn't work* with react 17 yet.

This is a duplicate of #2429.

**Closed by ljharb** 2021-02-22 22:39 UTC

**Comment by daveisfera** [comment] 2021-02-22 22:53
Sorry, I had done a search for `React 17`, but apparently I didn't look far enough down the list
