### ISSUE TITLE
Cheerio in Enzyme 3.11.0 isn't pinned to the right version

### ISSUE THREAD

**Issue by Alevale** [enzymejs/enzyme#2607] opened 2024-08-12 13:14 UTC
### Current behavior

When using the version of enzyme `3.11.0` we are using under the hood cheerio

Cheerio is evolving and as of their `1.0.0`version (released 3 days ago) they don't expose the `lib` folder anymore in their new version.

This means we have to pin the dependency to `"cheerio": "=1.0.0-rc.3",` in the latest enzyme package like it is in master.

This is breaking the package with the following message

> Module not found: Error: Package path ./lib/utils is not exported from package /builds/some-app/node_modules/cheerio (see exports field in /some-app/node_modules/cheerio/package.json)

### Expected behavior

When I use enzime I don't have to create overrides for external libraries in my own project

### Your environment

Does not apply

### Related issues

https://github.com/cheeriojs/cheerio/issues/4001

**Comment by ljharb** [comment] 2024-08-13 02:53
Duplicate of #2558, already fixed in the next release.

**Closed by ljharb** 2024-08-13 02:53 UTC
